package com.tongbanjie.baymax.jdbc.model;

public class ExecuteCommand {
	
	private ExecuteMethod method;	// 需要执行的方法
	private Object[] args;			// 方法的参数,[0]必须是String类型的SQL
	boolean autoGeneratedKeys;		// 执行完后是否需要获取自动生成键的ResultSet
	
	public ExecuteCommand(ExecuteMethod method, Object[] args, boolean autoGeneratedKeys){
		this.method = method;
		this.args = args;
		this.autoGeneratedKeys = autoGeneratedKeys;
	}
	
	public ExecuteMethod getMethod() {
		return method;
	}
	public void setMethod(ExecuteMethod method) {
		this.method = method;
	}
	public Object[] getArgs() {
		return args;
	}
	public void setArgs(Object[] args) {
		this.args = args;
	}
	public boolean isAutoGeneratedKeys() {
		return autoGeneratedKeys;
	}
	public void setAutoGeneratedKeys(boolean autoGeneratedKeys) {
		this.autoGeneratedKeys = autoGeneratedKeys;
	}
	
	public String toString() {
		StringBuilder buffer = new StringBuilder();
		buffer.append(method).append("(");
		if(args != null && args.length > 0){
			for (int i = 0; i < args.length; ++i) {
				buffer.append(args[i]);
				if (i != args.length - 1) {
					buffer.append(", ");
				}
			}
		}
		buffer.append(")");
		return buffer.toString();
	}

}
